version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - '8000:8000'
    volumes:
      - ./requirements.txt:/app/requirements.txt