# Generated by Django 5.0.2 on 2024-02-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default=2, max_length=255, unique=True, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
