# Generated by Django 5.0.2 on 2024-03-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birth',
            name='First_Name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='birth',
            name='Last_Name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='birth',
            name='Other_Name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name'),
        ),
    ]
