# Generated by Django 5.0.2 on 2024-03-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_birth_first_name_alter_birth_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birth',
            name='CIN',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='CIN'),
        ),
    ]
