# Generated by Django 5.0.2 on 2024-03-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_birth_cin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birth',
            name='City',
            field=models.CharField(max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='birth',
            name='Father_ID_Number',
            field=models.CharField(max_length=255, verbose_name='ID Number'),
        ),
        migrations.AlterField(
            model_name='birth',
            name='Mother_ID_number',
            field=models.CharField(max_length=255, verbose_name='ID Number'),
        ),
        migrations.AlterField(
            model_name='birth',
            name='Place_of_Birth',
            field=models.CharField(max_length=255, verbose_name='State'),
        ),
    ]
