# Generated by Django 5.0.2 on 2024-03-04 15:44

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_birth_city_alter_birth_father_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birth',
            name='Father_DOB',
            field=models.DateField(blank=True, max_length=255, verbose_name="Father's DOB"),
        ),
        migrations.AlterField(
            model_name='birth',
            name='Father_First_Name',
            field=models.CharField(blank=True, max_length=255, verbose_name="Father's First Name"),
        ),
        migrations.AlterField(
            model_name='birth',
            name='Father_ID_Number',
            field=models.CharField(blank=True, max_length=255, verbose_name="Father's ID Number"),
        ),
        migrations.AlterField(
            model_name='birth',
            name='Father_ID_type',
            field=models.CharField(blank=True, choices=[('G', 'Ghana Card'), ('V', "Voter's ID"), ('N', 'NHIS'), ('D', "Driver's License"), ('P', 'Passport')], max_length=255, verbose_name="Father's ID Type"),
        ),
        migrations.AlterField(
            model_name='birth',
            name='Father_Last_Name',
            field=models.CharField(blank=True, max_length=255, verbose_name="Father's Last Name"),
        ),
        migrations.AlterField(
            model_name='birth',
            name='Father_Nationality',
            field=django_countries.fields.CountryField(max_length=255, verbose_name="Father's Nationality"),
        ),
        migrations.AlterField(
            model_name='birth',
            name='First_Name',
            field=models.CharField(blank=True, max_length=255, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='birth',
            name='Last_Name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='birth',
            name='Mother_DOB',
            field=models.DateField(max_length=255, verbose_name="Mother's DOB"),
        ),
        migrations.AlterField(
            model_name='birth',
            name='Mother_First_Name',
            field=models.CharField(blank=True, max_length=255, verbose_name="Mother's First Name"),
        ),
        migrations.AlterField(
            model_name='birth',
            name='Mother_ID_number',
            field=models.CharField(max_length=255, verbose_name="Mother's ID Number"),
        ),
        migrations.AlterField(
            model_name='birth',
            name='Mother_ID_type',
            field=models.CharField(blank=True, choices=[('G', 'Ghana Card'), ('V', "Voter's ID"), ('N', 'NHIS'), ('D', "Driver's License"), ('P', 'Passport')], max_length=255, verbose_name="Mother's ID Type"),
        ),
        migrations.AlterField(
            model_name='birth',
            name='Mother_Last_Name',
            field=models.CharField(blank=True, max_length=255, verbose_name="Mother's Last Name"),
        ),
        migrations.AlterField(
            model_name='birth',
            name='Mother_Nationality',
            field=django_countries.fields.CountryField(max_length=255, verbose_name="Mother's Nationality"),
        ),
        migrations.AlterField(
            model_name='birth',
            name='Other_Name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Other Names'),
        ),
        migrations.AlterField(
            model_name='birth',
            name='Place_of_Birth',
            field=models.CharField(max_length=255, verbose_name='Place Of Birth'),
        ),
    ]
