# Generated by Django 5.0.2 on 2024-03-05 10:22

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_birth_father_dob_alter_birth_father_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='birth',
            name='Father_Phone_Number',
            field=models.IntegerField(blank=True, default=0, verbose_name="Father's Phone Number"),
        ),
        migrations.AddField(
            model_name='birth',
            name='Informant_Phone_Number',
            field=models.IntegerField(blank=True, default=0, verbose_name="Informant's Phone Number"),
        ),
        migrations.AddField(
            model_name='birth',
            name='Mother_Phone_Number',
            field=models.IntegerField(blank=True, default=0, verbose_name="Mother's Phone Number"),
        ),
        migrations.AlterField(
            model_name='birth',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birth', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(blank=True, verbose_name='Phone Number'),
        ),
        migrations.CreateModel(
            name='Death',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, max_length=255, verbose_name='Surname')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='First Name')),
                ('Other_Name', models.CharField(blank=True, max_length=255, verbose_name='Other Name')),
                ('birth_date', models.DateField(blank=True, verbose_name='Birth Date')),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender')),
                ('Nationality', django_countries.fields.CountryField(max_length=2, verbose_name='Nationality')),
                ('ID_Type', models.CharField(blank=True, choices=[('G', 'Ghana Card'), ('V', "Voter's ID"), ('N', 'NHIS'), ('D', "Driver's License"), ('P', 'Passport')], max_length=1, verbose_name='ID_Type')),
                ('ID_Number', models.CharField(blank=True, max_length=1, verbose_name='ID_Number')),
                ('Residence_addr', models.CharField(max_length=255, verbose_name='Residence Address')),
                ('Date_of_Death', models.DateField(blank=True, verbose_name='Death Date')),
                ('Cause_of_Death', models.TextField(blank=True, verbose_name='Cause of Death')),
                ('Place_of_Death', models.TextField(blank=True, verbose_name='Place of Death')),
                ('Address_of_place', models.TextField(blank=True, verbose_name='Address of Place')),
                ('Informant_Name', models.CharField(blank=True, max_length=255, verbose_name='Informant Name')),
                ('Informant_ID_Type', models.CharField(blank=True, choices=[('G', 'Ghana Card'), ('V', "Voter's ID"), ('N', 'NHIS'), ('D', "Driver's License"), ('P', 'Passport')], max_length=255, verbose_name='ID_Type')),
                ('Informant_ID_Number', models.CharField(blank=True, max_length=255, verbose_name='ID_Number')),
                ('Relationship_Type', models.CharField(blank=True, choices=[('P', 'Parent'), ('S', 'Sibling'), ('Se', 'Self'), ('G', 'Guardian'), ('O', 'Other')], max_length=255, verbose_name='Relationship Type')),
                ('Phone_Number', models.IntegerField(blank=True, default=0, verbose_name='Phone Number')),
                ('Email_Address', models.EmailField(blank=True, max_length=255, verbose_name='Email Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deaths', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
