# Generated by Django 5.0.2 on 2024-03-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='death',
            name='ID_Number',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID_Number'),
        ),
    ]
