# Generated by Django 5.0.2 on 2024-03-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_death_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='death',
            name='Burial_Status',
            field=models.CharField(blank=True, choices=[('B', 'Buried'), ('N', 'Not Buried')], default='N', max_length=1, verbose_name='Burial Status'),
        ),
    ]
