# Generated by Django 5.0.2 on 2024-03-18 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_birthrecord_deathrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthrecord',
            old_name='user',
            new_name='recorder',
        ),
        migrations.RemoveField(
            model_name='birthrecord',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='birthrecord',
            name='name',
        ),
        migrations.AddField(
            model_name='birthrecord',
            name='action_type',
            field=models.CharField(default='Birth added', max_length=50),
        ),
        migrations.AddField(
            model_name='birthrecord',
            name='birth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.birth'),
        ),
        migrations.AddField(
            model_name='birthrecord',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='birthrecord',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
