# Generated by Django 5.0.2 on 2024-03-18 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_user_birthrecord_recorder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deathrecord',
            old_name='user',
            new_name='recorder',
        ),
        migrations.RemoveField(
            model_name='deathrecord',
            name='date_of_death',
        ),
        migrations.RemoveField(
            model_name='deathrecord',
            name='name',
        ),
        migrations.AddField(
            model_name='deathrecord',
            name='action_type',
            field=models.CharField(default='Death recorded', max_length=50),
        ),
        migrations.AddField(
            model_name='deathrecord',
            name='death',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.death'),
        ),
        migrations.AddField(
            model_name='deathrecord',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deathrecord',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='birthrecord',
            name='action_type',
            field=models.CharField(default='Birth recorded', max_length=50),
        ),
    ]
