# Generated by Django 5.0.2 on 2024-04-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_deathrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birth',
            old_name='date_of_birth',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='death',
            old_name='Date_of_Death',
            new_name='Date',
        ),
        migrations.AlterField(
            model_name='birthrecord',
            name='details',
            field=models.TextField(blank=True, default='none'),
        ),
        migrations.AlterField(
            model_name='deathrecord',
            name='details',
            field=models.TextField(blank=True, default='none'),
        ),
    ]
