# Generated by Django 5.0.2 on 2024-04-04 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_date_of_birth_birth_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='death',
            old_name='Date',
            new_name='date',
        ),
    ]
