# Generated by Django 5.0.2 on 2024-04-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_date_death_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birth',
            name='Father_Nationality',
            field=models.CharField(max_length=255, verbose_name="Father's Nationality"),
        ),
        migrations.AlterField(
            model_name='birth',
            name='Mother_Nationality',
            field=models.CharField(max_length=255, verbose_name="Mother's Nationality"),
        ),
    ]
