# Generated by Django 5.0.2 on 2024-09-22 11:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default=0, max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Phone Number'),
        ),
    ]
