# Generated by Django 5.0.2 on 2024-09-22 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default=0, max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Phone Number'),
        ),
    ]
